title: My Math Academy
description: “Courses · Tutorials · Exercises”
theme: jekyll-theme-cayman     # or minima, jekyll-theme-primer, etc.
plugins:
  - jekyll-feed
  - jekyll-sitemap
permalink: pretty
