# ────────────────────────────────────────────────────────────────────
# Site settings
# ────────────────────────────────────────────────────────────────────
title: My Math Academy
email: your-email@example.com
description: "Courses · Tutorials · Exercises"
baseurl: ""                 # change to "/<repo>" if not on user/org root
url: "https:/sooyong-liam.github.io"

# ────────────────────────────────────────────────────────────────────
# Theme
# ────────────────────────────────────────────────────────────────────
theme: null
remote_theme: mikemcquaid/just-the-docs@v0.4.0
plugins:
  - jekyll-feed            # RSS
  - jekyll-sitemap         # sitemap.xml

# ────────────────────────────────────────────────────────────────────
# Collections (optional)
# ────────────────────────────────────────────────────────────────────
collections:
  courses:
    output: true
    permalink: /courses/:path/

# ────────────────────────────────────────────────────────────────────
# Build settings
# ────────────────────────────────────────────────────────────────────
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
timezone: America/New_York

# ────────────────────────────────────────────────────────────────────
# Exclude from build
# ────────────────────────────────────────────────────────────────────
exclude:
  - Gemfile
  - Gemfile.lock
