# ────────────────────────────────────────────────────────────────────
# Site settings
# ────────────────────────────────────────────────────────────────────
title: "My Math Academy"
description: "Courses · Tutorials · Exercises"
baseurl: ""            # change to "/<repo>" if not serving from user/org root
url: "https://<your-username>.github.io"

# ────────────────────────────────────────────────────────────────────
# Theme: pin to the last GH-Pages–compatible version
# ────────────────────────────────────────────────────────────────────
remote_theme: mmistakes/minimal-mistakes@4.24.0
theme: null

# ────────────────────────────────────────────────────────────────────
# Plugins
# ────────────────────────────────────────────────────────────────────
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mathjax
  - jekyll-include-cache   # this provides the include_cached tag

# ────────────────────────────────────────────────────────────────────
# Markdown & MathJax
# ────────────────────────────────────────────────────────────────────
markdown: kramdown
kramdown:
  math_engine: mathjax
mathjax:
  version: "3.0"
  config: "TeX-AMS_HTML"

# ────────────────────────────────────────────────────────────────────
# Collections
# ────────────────────────────────────────────────────────────────────
collections:
  courses:
    output: true
    permalink: /courses/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  exercises:
    output: true
    permalink: /exercises/:path/

# ────────────────────────────────────────────────────────────────────
# Navigation
# ────────────────────────────────────────────────────────────────────
navbar:
  title: "My Math Academy
