# ────────────────────────────────────────────────────────────────────
# Site settings
# ────────────────────────────────────────────────────────────────────
title: My Math Academy
description: Courses · Tutorials · Exercises
baseurl: ""            # e.g. "/my-repo" if not serving from user/org root
url: https://<your-username>.github.io

# ────────────────────────────────────────────────────────────────────
# Theme: pin to a GitHub Pages–compatible release
# ────────────────────────────────────────────────────────────────────
remote_theme: mmistakes/minimal-mistakes@4.24.0
theme: null

# ────────────────────────────────────────────────────────────────────
# Plugins
# ────────────────────────────────────────────────────────────────────
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mathjax
  - jekyll-include-cache

# ────────────────────────────────────────────────────────────────────
# Markdown & MathJax
# ────────────────────────────────────────────────────────────────────
markdown: kramdown
kramdown:
  parse_block_html: true
  math_engine: mathjax
mathjax:
  version: "3.0"
  config: "TeX-AMS_HTML"

# ────────────────────────────────────────────────────────────────────
# Collections
# ────────────────────────────────────────────────────────────────────
collections:
  courses:
    output: true
    permalink: /courses/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  exercises:
    output: true
    permalink: /exercises/:path/

# ────────────────────────────────────────────────────────────────────
# Navigation
# ────────────────────────────────────────────────────────────────────
navbar:
  title: My Math Academy
  items:
    - title: Courses
      url: /courses/
    - title: Blog
      url: /blog/
    - title: Exercises
      url: /exercises/
    - title: About
      url: /about/

# ────────────────────────────────────────────────────────────────────
# Defaults
# ────────────────────────────────────────────────────────────────────
defaults:
  - scope:
      type: posts
    values:
      layout: single
      author: Your Name
  - scope:
      type: courses
    values:
      layout: single
  - scope:
      type: exercises
    values:
      layout: single

# ────────────────────────────────────────────────────────────────────
# Build settings
# ────────────────────────────────────────────────────────────────────
permalink: pretty
timezone: America/New_York
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
